/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordRouteImport } from './routes/word'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as IndexRouteImport } from './routes/index'

const WordRoute = WordRouteImport.update({
  id: '/word',
  path: '/word',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/word': typeof WordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/word': typeof WordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels': typeof LevelsRoute
  '/practice': typeof PracticeRoute
  '/word': typeof WordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/levels' | '/practice' | '/word'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels' | '/practice' | '/word'
  id: '__root__' | '/' | '/levels' | '/practice' | '/word'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsRoute: typeof LevelsRoute
  PracticeRoute: typeof PracticeRoute
  WordRoute: typeof WordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word': {
      id: '/word'
      path: '/word'
      fullPath: '/word'
      preLoaderRoute: typeof WordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsRoute: LevelsRoute,
  PracticeRoute: PracticeRoute,
  WordRoute: WordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
